import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner"; // <--- INI PENTING

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meds Game",
  description: "Medical simulation game generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>{children}</main>
        <Toaster position="top-center" richColors /> {/* <--- INI WAJIB ADA */}
      </body>
    </html>
  );
}